// Authoritative subject vocabulary supplied by the project owner, 2026-09-16.
// Distinct valid codes remain distinct even when their subject names overlap.
export const PITT_SUBJECTS: Readonly<Record<string,string>> = {
  "ACCT": "Accounting",
  "ACITP": "Interpreter for Deaf Training",
  "ADMJ": "Administration of Justice",
  "AFRCNA": "Africana Studies",
  "AFROTC": "Aero-Space Studies",
  "ANTH": "Anthropology",
  "ARABIC": "Arabic",
  "ARC": "Architectural Studies",
  "ART": "Art",
  "ARTSC": "Arts and Sciences",
  "ASL": "American Sign Language",
  "ASTRON": "Astronomy",
  "ATHLTR": "Athletic Training",
  "BCMS": "Bosnian-Croatian-Montenegrin-Serbian",
  "BIOENG": "Bioengineering",
  "BIOETH": "Bioethics",
  "BIOL": "Biology",
  "BIOSC": "Biological Sciences",
  "BUS": "Business",
  "BUSACC": "Accounting",
  "BUSBIS": "Business Information Systems",
  "BUSECN": "Business Economics",
  "BUSENV": "Business Environment",
  "BUSERV": "Business Service",
  "BUSFIN": "Finance",
  "BUSHRM": "Human Resources Management",
  "BUSMKT": "Marketing",
  "BUSORG": "Organizational Behavior",
  "BUSQOM": "Quantitative Methods/Operations Management",
  "BUSSCM": "Supply Chain Management",
  "BUSSPP": "Strategic Planning & Policy",
  "CAS": "College of Arts and Sciences",
  "CDACCT": "Career Development Accounting",
  "CE": "Civil Engineering",
  "CEE": "Civil & Environmental Engineering",
  "CGS": "College of General Studies",
  "CHE": "Chemical Engineering",
  "CHEM": "Chemistry",
  "CHIN": "Chinese",
  "CIST": "Computer Information Systems & Technology",
  "CJ": "Criminal Justice",
  "CLASS": "Classics",
  "CLP": "Comparative Literature",
  "CLRES": "Clinical Research",
  "CMPINF": "Computing and Information",
  "COE": "Computer Engineering",
  "COMM": "Communication",
  "COMMRC": "Communication: Rhetoric & Communication",
  "COUN": "Clinical Rehabilitation and Mental Health Counseling",
  "CRIM": "Criminal Justice",
  "CS": "Computer Science",
  "CSD": "Communication Science and Disorders",
  "DENHYG": "Dental Hygiene",
  "DENT": "Dental Medicine",
  "DSPHL": "Dental Pharmacology",
  "DUCATH": "Catholic Studies",
  "EAS": "East Asian Studies",
  "ECE": "Electrical and Computer Engineering",
  "ECED": "Early Childhood Education",
  "ECON": "Economics",
  "EDPSY": "Educational Psychology",
  "EDUC": "Education",
  "EE": "Electrical Engineering",
  "EET": "Electrical Engineering Technology",
  "EFOP": "Educational Foundations, Organization, & Policy",
  "EGET": "Energy Engineering Technology",
  "ELED": "Elementary Education",
  "ELI": "English Language Institute",
  "EM": "Emergency Medicine",
  "ENG": "English",
  "ENGCMP": "English Composition",
  "ENGFLM": "English Film Studies",
  "ENGLIT": "English Literature",
  "ENGLSH": "English",
  "ENGR": "Engineering",
  "ENGSCI": "Engineering Science",
  "ENGWRT": "English Writing",
  "ENTR": "Entrepreneurship",
  "ENVSTD": "Environmental Studies",
  "ES": "Environmental Science",
  "EST": "Energy Science and Technology",
  "ET": "Engineering Technology",
  "EXLA": "Experiential Learning – Arts & Sciences",
  "EXLG": "Experiential Learning – Education",
  "EXLH": "Experiential Learning – Engineering",
  "EXLI": "Experiential Learning – SHRS",
  "EXLJ": "Experiential Learning – Sciences",
  "EXLK": "Experiential Learning – SPIA",
  "EXLL": "Experiential Learning – Social Work",
  "EXLP": "Experiential Learning – Nursing",
  "EXLQ": "Experiential Learning – Pharmacy",
  "EXLR": "Experiential Learning – Public Health",
  "EXSCI": "Exercise Science",
  "FA": "Fine Arts",
  "FDSED": "Foundations of Education",
  "FILMST": "Film Studies",
  "FIN": "Finance",
  "FMST": "Film and Media Studies",
  "FORSCI": "Forensic Science",
  "FP": "Freshman Program",
  "FR": "French",
  "FS": "Freshman Studies",
  "GEO": "Geosciences and the Environment",
  "GEOG": "Geography",
  "GEOL": "Geology",
  "GER": "German",
  "GREEK": "Greek",
  "GREEKM": "Modern Greek",
  "GRO": "Gas, Renewables, and Oil Engineering",
  "GSWS": "Gender, Sexuality & Women's Studies",
  "HAA": "History of Art & Architecture",
  "HCM": "Healthcare Management",
  "HEBREW": "Hebrew",
  "HHD": "Health and Human Development",
  "HI": "Health Informatics",
  "HINDI": "Hindi",
  "HIST": "History",
  "HLTHCR": "Healthcare",
  "HMGT": "Hospitality Management",
  "HONORS": "Honors",
  "HPEDU": "HPEDU",
  "HPRED": "Health Physical & Recreation Education",
  "HPS": "History and Philosophy of Science",
  "HRP": "Health Related Professions",
  "HRS": "Health and Rehabilitation Sciences",
  "HUMAN": "Humanities",
  "HUN": "Hungarian",
  "IA": "Interdisciplinary Arts",
  "IE": "Industrial Engineering",
  "IL": "Instruction and Learning",
  "INDIST": "Interdisciplinary Studies",
  "INFSCI": "Information Science",
  "INTS": "International Studies",
  "IRISH": "Irish",
  "IS": "Information Systems",
  "IT": "Instructional Technology",
  "ITAL": "Italian",
  "JOURNL": "Journalism",
  "JPNSE": "Japanese",
  "JS": "Jewish Studies",
  "KOREAN": "Korean",
  "LATIN": "Latin",
  "LCJS": "Law, Criminal Justice & Society",
  "LCTL": "Less Commonly Taught Languages",
  "LDRSHP": "Leadership",
  "LEGLST": "Legal Studies",
  "LING": "Linguistics",
  "LNSK": "Learning Skills",
  "MATH": "Mathematics",
  "ME": "Mechanical Engineering",
  "MEMS": "Mechanical Engineering & Materials Science",
  "MET": "Mechanical Engineering Technology",
  "MGMT": "Management",
  "MILS": "Military Science & Tactics",
  "MIS": "Management Information Systems",
  "MLED": "Middle Level Education",
  "MRKT": "Marketing",
  "MRST": "Medieval & Renaissance Studies",
  "MUSIC": "Music",
  "NATSC": "Natural Science",
  "NPHS": "National Preparedness & Homeland Security",
  "NROSCI": "Neuroscience",
  "NUR": "Nursing",
  "NUTR": "Nutrition",
  "OCS": "Oral and Craniofacial Science",
  "PEDC": "Co-Ed Physical Education",
  "PERS": "Persian (Farsi)",
  "PET": "Petroleum Technology",
  "PETE": "Petroleum Engineering",
  "PHARM": "Pharmacy",
  "PHIL": "Philosophy",
  "PHYS": "Physics",
  "PHYSTA": "Physical Therapist Assistant",
  "PIA": "Public & International Affairs",
  "PITT": "PITT",
  "PO": "Prosthetics and Orthotics",
  "POLISH": "Polish",
  "PORT": "Portuguese",
  "PR": "Public Relations",
  "PS": "Political Science",
  "PSY": "Psychology",
  "PSYED": "Psychology in Education",
  "PUBHLT": "Public Health",
  "PUBSRV": "Public Service",
  "QUECH": "Quechua/Kichwa",
  "RADSC": "Radiological Science",
  "REHSCI": "Rehabilitation Science",
  "RELGST": "Religious Studies",
  "RESCA": "Respiratory Care",
  "RT": "Rehabilitation Technology",
  "RUSS": "Russian",
  "SA": "Studio Arts",
  "SCED": "Secondary Education",
  "SERCRO": "Serbo-Croatian",
  "SETHL": "Seton Hill College",
  "SLAV": "Slavic",
  "SLI": "Slavic Language Institute – Non-Slavic",
  "SLOVAK": "Slovak",
  "SOC": "Sociology",
  "SOCSCI": "Social Sciences",
  "SOCWRK": "Social Work",
  "SPAN": "Spanish",
  "SPLED": "Special Education",
  "STAT": "Statistics",
  "SURTEC": "Surgical Technology",
  "SWAHIL": "Swahili",
  "SWE": "Swedish",
  "THEA": "Theatre Arts",
  "TLL": "Teaching, Learning and Leading",
  "TURKSH": "Turkish",
  "UKRAIN": "Ukrainian",
  "URBNST": "Urban Studies",
  "VIET": "Vietnamese",
  "WCC": "Westmoreland Community College",
  "WOMNST": "Women's Studies",
  "WRITNG": "Writing"
};
export const PITT_SUBJECT_CODES = Object.keys(PITT_SUBJECTS);

// Unambiguous spelling repairs preserve the supplied course number.
export const SUBJECT_TYPOS: Readonly<Record<string,string>> = {
  BUSMT:'BUSMKT',BSMKT:'BUSMKT',BUMKT:'BUSMKT',BUSMK:'BUSMKT',NEUROSCI:'NROSCI',
};
// These names/abbreviations require same-professor, same-number corroboration.
export const SUBJECT_ABBREVIATIONS: Readonly<Record<string,readonly string[]>> = {
  CALC:['MATH'],CALCULUS:['MATH'],MATHS:['MATH'],MUS:['MUSIC'],
  MKT:['BUSMKT','MRKT'],MKTG:['BUSMKT','MRKT'],NEURO:['NROSCI'],
};
