-- Preserve all existing tags; allow the expanded extraction vocabulary.
ALTER TABLE tags DROP CONSTRAINT IF EXISTS tags_tag_type_check;
ALTER TABLE tags ADD CONSTRAINT tags_tag_type_check CHECK (tag_type IN (
  'notecard_allowed',
  'open_book_exam',
  'online_exams',
  'no_cumulative_final',
  'curve_applied',
  'attendance_not_required',
  'easy_a_explicit_mention',
  'group_project_heavy',
  'online_quizzes',
  'unlimited_quiz_attempts',
  'take_home_exam',
  'unproctored_exam',
  'multiple_choice_only',
  'predictable_exam_format',
  'exam_reuses_old_questions',
  'provides_study_guide',
  'posts_slides_or_notes',
  'practice_exam_provided',
  'review_session_before_exam',
  'allows_past_exams',
  'drops_lowest_score',
  'extra_credit_offered',
  'generous_curve',
  'participation_based_grading',
  'effort_based_grading',
  'no_late_penalty',
  'light_homework_load',
  'no_homework',
  'flexible_deadlines',
  'few_graded_assignments',
  'gpa_booster_mention'
));
